### ISSUE TITLE
Problems installing virtual environment

### ISSUE THREAD

**Issue by angelrls** [pykoala/pykoala#431]
Hi, I've followed 

https://pykoala.readthedocs.io/en/latest/getting-started/virtual-environment.html

to install a virtual environment and it failed in the second step: source venv_koala/bin/activate

Thanks James for helping me fixing this. The issue is that my terminal are tcsh, so I had to do:

source venv_koala/bin/activate.csh

We should include this in the documentation, also say that you need to git clone https://github.com/pykoala/koala.git before installing the virtual environment.  

(3h later after extensive help by Miguel)

Something important that Miguel needs to add:

python3 -m ipykernel install --user --name=venv_koala

I got it working in Jupyter notebook, tested the standard star tutorial and worked, but now Spyder is failing again to run my own version of the code :((((

Unfortunately, I don't think I'll be able to do anything else till my Friday morning. But at least I got the latest version of PyKOALA installed in my laptop as requested and working.

Thanks,

**Comment by angelrls** [comment]
A follow-up: I realised that this installation messed up with my full Python installation. It was extremely frustrating.

After a couple of extra hours with Miguel on Friday morning, and my frustration rising because of all the problems we found in my laptop, we gave up this approach so far. It seems I need to re-install everything (including operating system) in my laptop to get this working, I can't do this till August after my trips.

I re-installed everything Python as it works in my laptop (Anaconda), I'm running the code in Spyder and Jupyter without problems just adding the path to the latest version of PyKOALA to my sys.path and loading the PyKOALA tasks as needed.

This also made me to restart the kernel everytime I was changing something in the code (hence, it easily took me the double of time for doing changes that I used to).

After the full weekend in front of the laptop checking one by one every task, adding them one by one to the new version, and completing the documentation to all of them, I can say what I've done so far **works without problems** using the latest version of the code, as expected as I didn't change the main code (except for the 2 minor changes for which I submitted an issue).

The other change I'll request if updating run31 as the name of the object is wrong (is He2-10 and not Tol30), and updating the folder with the data (in my humble opinion, they should be organised by date/gratings, I'll create another issue about it).

Now, I would like to upload all of this to a new branch, including updated tutorials (where I have included much more detailed information and the right way of importing tasks) but I don't know exactly how this works (Miguel, I'll need your help here), just in case I did something funny with the other branch I pushed last week (that uses the April version of the code, you can delete/ignore that branch).

Also, as mentioned this week I'm attending a Conference in the Barossa Valley and I'm not sure if I would be able to join on Tuesday at my 3:30pm local time (in South Australia) as attending the talks. But I'll try.

Thanks.

**Comment by PabloCorcho** [comment]
I am going to fix the other issues + fits header now. I will merge them as hot fixes. I think the data in the tutorials could be stored as `tutorials/data/koala/grating.../*.fits` to avoid any confusion with other stuff (e.g. WEAVE)

To create a new branch from the current branch in which you are implementing the changes you can do `git checkout -b NEW_NAME`, you can add/commit things, and then `git push -u origin NEW_NAME`. Once the new branch is uploaded, I can test the tutorials on my machine so we ensure that they work in different OS/environments.

**Comment by PabloCorcho** [comment]
While changing the structure of the data for the tutorials (see [branch](https://github.com/pykoala/pykoala/tree/431_change_fits_header)) , I realized that the data we were using was quite heterogeneous (some nights from February, some others from September). In fact, in many tutorials, although there was the possibility of using the blue grism, there was no blue data to use (e.g. He2-10). What I have done is to change the structure, as explained in the previous comment, as well as making sure that there is both red and blue gratings data for: skyflats, std star, He2-10.

Now the problem is that there is too much data to keep in this repo (~500 Mb). On top of that,  when adding so many FITS binary files Github is even crashing when I create the PR using the web interface.

That has led me to move everything in that new branch to a pykoala tutorials [repository](https://github.com/pykoala/pykoala-tutorials). I think this is the best way to move forward. Actually, my intention is to create a set of tutorials following the same structure as the paper. For the tutorials of next week it is up to you where to store them (I can just update the file 31 with the name corrected), although the only difference would be that the users need to clone a second repository.

**Comment by PabloCorcho** [comment]
Pinging here @miguelglezb, @angelrls and @paranoya to avoid loss of information!

**Comment by miguelglezb** [comment]
Thanks Pablo! These changes are necessary and long overdue. While it is a challenge given the time left, I think it will be worthwhile to make all the tutorials work from here and just ask people to install both repos during the training. I'm already working on the notebooks to fix some bugs present, mainly due to errors with the relative paths for some data. I will make a PR this weekend with all the corrections.

**Comment by PabloCorcho** [comment]
What sort of errors are you finding? Could you post them on a separate issue?

I think the tutorials should be only located in a single place. Ff you want to keep updating them from this repo, then the tutorials repository should not be mentioned at all during the workshop (maybe just mentioning that in the future there will be a dedicated repo for tutorials).

**Comment by MennaEwas** [comment]
I found this command helpful in activating the virtual environment after creation in vs code terminal

`Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process`
