### ISSUE TITLE
PyKOALA repository name refactoring

### ISSUE THREAD

**Issue by PabloCorcho** [pykoala/pykoala#436]
Currently, the name of the repository is `koala`. This needs to be replaced by `pykoala` to maintain consistency with the src code name convention. I believe this should be done before the tutorials since the users would have to change the URL otherwise.

The change is simple, but we would have to update the local URL of the repository as:

For HTTPS protocol
```
git remote set-url origin https://github.com/pykoala/pykoala.git
```
For SSH protocol
```
git remote set-url origin git@github.com:pykoala/pykoala.git
```

If you are not sure which protocol you are using, you can run `git remote -v` to know which URL was set before.

**Comment by PabloCorcho** [comment]
@paranoya @miguelglezb @angelrls please let me know what are your thoughts about this.

**Comment by paranoya** [comment]
I fully agree

**Comment by miguelglezb** [comment]
I've been thinking the same for awhile, agreed!

**Comment by angelrls** [comment]
Thanks a lot. Please, go for it, yes, I think it was also in my mind to mention it, but too many things as usual...

Thanks a lot for the hard work on this and patience you are having with me. Apologies again I can't do much more till Friday as busy in the conference and we have a "laptops not allowed" policy at the Conference Room. Instead of wine tasting around the Barossa Valley this afternoon (everyone went to that), I'm preparing my invited talk for tomorrow. Many people have already asked me about PyKOALA, in a couple of talks some preliminarily results have been shown using KOALA. I'll include a little bit in my talk.

I'm also sending an email to participants of the reduction tutorial now.

Thanks again,

**Comment by PabloCorcho** [comment]
@paranoya,  @miguelglezb, @angelrls I will change it now.
